modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="MIT"
issueTrackerURL="https://github.com/craftablescience/Half-Craft/issues" #optional
[[mods]] #mandatory
modId="halfcraft" #mandatory
version="0.0.1" #mandatory
displayName="Half-Craft" #mandatory
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="logo.png"
#credits="Black Mesa Staff" #optional
#authors="Love, Cheese and small house plants" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A mod that aims to add several features from Half-Life and other games in that universe to Minecraft.
'''
[[dependencies.halfcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.halfcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.halfcraft]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.33,4.0)"
    ordering="BEFORE"
    side="BOTH"